In [5]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML



class OrBi():
    def __init__(self, mat):
        self.mat = mat
        self.df = pd.DataFrame(mat)  
        
        
    def gini_mu(self, rows,cols):
        _, r_mu = self.r_par(cols)
        _, c_mu = self.c_par(rows)
        return r_mu+c_mu-r_mu*c_mu
        
        
    def r_par(self,cols):    
#         display(self.df.loc[:,cols])
        display(self.df.style.applymap(self._bg_map,
                               subset=pd.IndexSlice[:,cols]))
        
        mat_pat,index, counts = np.unique(self.mat[:,cols],axis=0,return_index=1, return_counts=1)
#         print(mat_pat,index,counts)

        display(pd.DataFrame(mat_pat, index=[counts,index]))
        print(np.power(2,np.sum(mat_pat,axis=1)))

        

        
        gini = 1 - np.sum(np.square(counts/np.sum(counts)))        
        gini_m = 1 - np.dot(np.square(counts/np.sum(counts)), 
                            np.power(2,np.sum(mat_pat,axis=1)))
        print(f'For row partitions on cols of{cols}:\n\n \
                gini : {gini}\n   \
              gini_m : {gini_m}           ')
        return gini, gini_m
        
        
        
    def c_par(self,rows):    
#         display(self.df.loc[:,rows])
        display(self.df.style.applymap(self._bg_map,
                               subset=pd.IndexSlice[rows,:]))
        
        
        mat_pat,index, counts = np.unique(self.mat[rows,:],axis=1,return_index=1, return_counts=1)
        

        print(mat_pat,index,counts)
        display(pd.DataFrame(mat_pat, columns=[counts,index]))
        print(np.power(2,np.sum(mat_pat,axis=0)))
        
        gini = 1 - np.sum(np.square(counts/np.sum(counts)))        
        gini_m = 1 - np.dot(np.square(counts/np.sum(counts)), 
                            np.power(2, np.sum(mat_pat,axis=0)))
        print(f'For column partitions on cols of{rows}:\n\n \
                gini : {gini}\n   \
              gini_m : {gini_m}           ')
        return gini, gini_m
        
    def proj(self, row, cols):
        
        print(f'Projections of columns {cols} on row {row}')
        return self.df.style.applymap(self._bg_map,
                               subset=pd.IndexSlice[row,cols])
    def rstr(self, col, rows):
        
        print(f'Restriction of rows {rows} on column {col}')        
        return self.df.style.applymap(self._bg_map,
                               subset=pd.IndexSlice[rows,col])
    
        
    def _bg_map(self,val, color='yellow'):
        return f'background-color: {color}'

In [6]:

size = (5, 5)
mat = np.random.choice([1,0],size)

orbi = OrBi(mat)
orbi.gini_mu([2,3],[2,3])

0  1
2 3  0  0
3 0  1  1

[1 4]
For row partitions on cols of[2, 3]:

                 gini : 0.48
                 gini_m : -0.6000000000000001           


[[0 1 1]
 [0 0 1]] [4 1 0] [1 3 1]


1  3  1
   4  1  0
0  0  1  1
1  0  0  1

[1 2 4]
For column partitions on cols of[2, 3]:

                 gini : 0.5599999999999999
                 gini_m : 0.07999999999999996           


-0.47200000000000014

In [94]:

size = (5, 5)
mat = np.random.choice([1,0],size)

orbi = OrBi(mat)

# orbi.proj(2,[2,3])
orbi.r_par([2,3])



0  1
2 1  0  1
  0  1  0
1 4  1  1

[0.16 0.16 0.04] [0.5 0.5 1. ]
For row partitions on cols of[2, 3]:

                 gini : 0.6399999999999999
                 gini_m : 0.7999999999999999           


(0.6399999999999999, 0.7999999999999999)

In [91]:
orbi.c_par([2,3])


[[0 0 1]
 [0 1 0]] [0 1 4] [3 1 1]


3  1   
   0  1  4
0  0  0  1
1  0  1  0

For column partitions on cols of[2, 3]:

                 gini : 0.5599999999999999
                 gini_m : 0.96           


(0.5599999999999999, 0.96)

0  1
2 2  0  0
  0  0  1
1 4  1  1

For row partitions on cols of[2, 3]:

                 gini : 0.6399999999999999
                 gini_m : 0.88           


[[0 0 1]
 [0 1 0]] [0 1 4] [3 1 1]


3  1   
   0  1  4
0  0  0  1
1  0  1  0

For column partitions on cols of[2, 3]:

                 gini : 0.5599999999999999
                 gini_m : 0.96           


0.9951999999999999

In [90]:
orbi.rstr(2,[2,3])

Restriction of rows [2, 3] on column 2


In [15]:
display(orbi.proj(2,[2,3]))
display(orbi.proj(2,[2,3]))

In [50]:
print(np.array([[1,1],[1,1],[1,0]]))
print(np.array([[1,1],[1,1],[1,0]]).shape)

a1,a2,a3,a4 = np.unique([[1,1],[1,1],[1,0]],axis=0,return_index=1, return_inverse=1,return_counts=1)
print(a1,a2,a3,a4)
np.sum(a1,axis=1)/a1.shape[1]


[[1 1]
 [1 1]
 [1 0]]
(3, 2)
[[1 0]
 [1 1]] [2 0] [1 1 0] [1 2]


array([0.5, 1. ])

In [27]:
mat[:,[2,3]]

array([[1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [41]:
a = np.array([1,2])
np.sum( np.square(a/2))

1.25

In [42]:
np.dot(a,a)

5

In [63]:
pd.DataFrame(mat,columns=[[1,2,3,4,5],[5,4,3,2,1]])

1  2  3  4  5
   5  4  3  2  1
0  0  0  1  1  1
1  0  0  0  0  1
2  0  1  1  0  1
3  1  1  0  1  1
4  0  0  0  1  1

In [97]:
np.power(2,a2)

array([4, 1])