In [1]:
from gini import *
size = (5, 5)
mat = np.random.choice([1,0],size)

orbi = OrBi(mat)
print(f'bicluster gini is: {orbi.gini_mu([2,3],[2,3])}')

Columns


[[0 0]
 [0 1]
 [1 0]
 [1 1]] [0 4 3 1] [2 1 1 1]
Partitions of columns on row


0  1
2 0  0  0
1 4  0  1
  3  1  0
  1  1  1

For row partitions on cols of[2, 3]:

                 gini : 0.72
                 gini_m : 0.9199999999999999           


Partitions of rows on columns
[[0 0 1]
 [0 1 1]] [1 2 0] [3 1 1]


3  1   
   1  2  0
0  0  0  1
1  0  1  1

For column partitions on cols of[2, 3]:

                 gini : 0.5599999999999999
                 gini_m : 0.94           
bicluster gini is: 0.9952
