In [1]:
import pandas as pd
import numpy as np
from reduce import *
from chengchurch import *

class Reduce_old:
    def __init__(self, mat):
        self.mat = mat
        self.row_sorted = np.argsort(np.sum(mat,axis=1))
        self.col_sorted = np.argsort(np.sum(mat,axis=0))
    def reduce(self,row,col):
        rows = np.sort(self.row_sorted[-row:])
        cols = np.sort(self.col_sorted[-col:])
        print(rows)
        print(cols)
        return self.mat[rows][:,cols]


    
class Reduce:
    def __init__(self, mat):
        self.mat = mat
        self._mat = mat

    def reduce(self,row,col):
        r_num = self.mat.shape[0] - row
        c_num = self.mat.shape[1] - col
        
        mi = min(r_num, c_num)
        for i in range(0, mi):
            self._reduce_row()
            self._reduce_col()
        else:
            if r_num > mi:
                for i in range(0,r_num-mi):
                    self._reduce_row()
            if c_num > mi:
                for i in range(0,c_num-mi):
                    self._reduce_col()
        return self._mat

        
    
    def _reduce_row(self):
        m = np.argmin(np.sum(self._mat,dtype=np.int32, axis = 1))
        self._mat = np.delete(self._mat,m,axis=0)
        print(f"\n{m}th row is deleted")
        print(self._mat)


    def _reduce_col(self):
        m = np.argmin(np.sum(self._mat,dtype=np.int32, axis = 0))
        self._mat = np.delete(self._mat,m,axis=1)
        print(f"\n{m}th col is deleted")
        print(self._mat)






In [4]:

size = (5, 5)
mat = np.random.choice([1,0],size)
print(mat)



[[0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [1 1 0 1 1]]


In [5]:

print("\nCheng&Church Bicluster")

biclusters = find_biclusters_np(mat, n_of_bicluster=1, msr_threshold=0.03)

best_bicluster = sorted(biclusters, key=lambda bicluster: bicluster.msr)[0]
print(get_bicluster(mat,best_bicluster))


Cheng&Church Bicluster
[[1 1 0 1 1]
 [1 1 0 1 1]]


In [9]:
print(mat)
matR = Reduce(mat)
print(matR.reduce(2,5))


[[0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [1 1 0 1 1]]

0th row is deleted
[[0 1 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [1 1 0 1 1]]

0th row is deleted
[[1 1 0 1 1]
 [1 1 0 1 0]
 [1 1 0 1 1]]

1th row is deleted
[[1 1 0 1 1]
 [1 1 0 1 1]]
[[1 1 0 1 1]
 [1 1 0 1 1]]
